### ISSUE TITLE
It didnt work

### ISSUE THREAD

**Issue by Unexplainablyweird1** [LinqToException/Fertilizer#2]
A black screen showed up but there was no green or red, and it just crashed, idont know if i was supposed to "extract" the fertilize zip file in the kynseed file, or outside,...................what am I supposed to do?

**Comment by LinqToException** [comment]
Did you read the [Getting Started](https://github.com/LinqToException/Fertilizer#getting-started) part? It should answer your question about where to extract it.

Just crashing is a bit weird, but I've never really fully tested Fertilizer in off-bounds situations (i.e. without the proper framework/extracted to the wrong location).

**Comment by Unexplainablyweird1** [comment]
I extracted it in the wrong location and did it wrong but I figured it out, ty
