### ISSUE TITLE
.Exe

### ISSUE THREAD

**Issue by ArtyBois** [LinqToException/Fertilizer#3]
So when I open up the fertilizer application it says that it can't find kynseed.exe. Is there something I should do differently?

**Comment by LinqToException** [comment]
Did you read the [Getting Started](https://github.com/LinqToException/Fertilizer#getting-started) part?

**Comment by ArtyBois** [comment]
yep, I made sure to read that. It said to download from the release page and the not code page right?

**Comment by LinqToException** [comment]
Correct, there's a few other steps after that though, and I suspect the second one is already going wrong.

**Comment by ArtyBois** [comment]
Should I it into the directory with or without the fertilizer-1.0.1 folder

**Comment by LinqToException** [comment]
Directly.

**Comment by ArtyBois** [comment]
Thank you, for some reason when I put it in directly earlier there was a whole string of commands I didn't recognize so I put it back into the folder but now its working

**Comment by LinqToException** [comment]
I guess I should add "clarify the docs" to my TODO list.
