### ISSUE TITLE
Kynseed error

### ISSUE THREAD

**Issue by Silaquix** [LinqToException/Fertilizer#4]
I'm not sure what's going on but the issue has only started in the last few days. I made an account to try to troubleshoot this since you're the creator. I've included a picture of the error message. I'm not a coder or even very tech-savvy so if I did anything wrong please let me know. 

![Kynseed Error](https://github.com/LinqToException/Fertilizer/assets/141271633/ffc65b08-abc6-411d-9904-21bf14b8e8e3)

**Comment by LinqToException** [comment]
Heya, that does not seem to be an issue from Fertilizer itself, but from one of the mods that you're using - one that fiddles with the Map/Map points as far as I can tell (MapPeople?). I've pinged some people to see who's responsible.

**Comment by Silaquix** [comment]
Thank you for the help.

**Comment by LinqToException** [comment]
It seems to be a known issue (or at least, happened in the past). I also saw that you've reported it over on the mod's page, so I'll close this issue for now as it isn't related to Fertilizer directly.

Best advice I can give right now is that I've heard it may happen in the deep mines when opening the map - so not not doing that there might help to prevent the crashes until the mod is fixed.
