### ISSUE TITLE
.Exe error

### ISSUE THREAD

**Issue by MagiKuiper** [LinqToException/Fertilizer#5]
So i try to use fertiliser but every time it says could not find Kynseed.exe, even though it says it's in the same folder, i've tried reinstalling but it didn't help. Is it because i'm running the GOG version?

**Comment by LinqToException** [comment]
That seems correct. Really strange. Just to make sure: Is there actually a Kynseed(.exe), or did GOG name it differently?

**Comment by MagiKuiper** [comment]
GOG named it "13"

**Comment by LinqToException** [comment]
Oh. That's weird. A quick fix would be to rename it to "Kynseed", run Fertilizer, then rename it back.

**Comment by MagiKuiper** [comment]
That actually helped, thank you a lot!
